run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - unparam
    - unused
    - deadcode
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
